# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 304984d4caa0af1cba97b74965103bbcae0767e35887f282a9ecdb6def78fb65962651e318f82df9f111fa409850af158ca936ba1627d43e88a7d364a47646c1

test:
  secret_key_base: 5c26d6166597fd73b1a47ad0143b814b1e5067c6efcf95da1c4276060c988da87210a1284e3c00f74ffb59f372d82eedcf0e3d6ff53060fcdfbbfa19db5ea593

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
